apiVersion: v1
data:
  APP_NAME: "CloudNativeMU"
  APP_ENV: "production"
  # APP_KEY:
  APP_DEBUG: "false"
  APP_TIMEZONE: "UTC"
  APP_URL: "https://cloudnativemauritius.alexbissessur.dev"
  ASSET_URL: "https://cloudnativemauritius.alexbissessur.dev"
  # URL: "0.0.0.0"

  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"

  APP_MAINTENANCE_DRIVER: "file"
  # APP_MAINTENANCE_STORE: database

  PHP_CLI_SERVER_WORKERS: "4"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  # DB_CONNECTION: mysql
  # DB_HOST: 127.0.0.1
  # DB_PORT: 3306
  # DB_DATABASE: laravel
  # DB_USERNAME: root
  # DB_PASSWORD: admin

  SESSION_DRIVER: database
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"

  CACHE_STORE: "database"
  CACHE_PREFIX: ""

  MEMCACHED_HOST: "127.0.0.1"

  VITE_APP_NAME: "${APP_NAME}"

  # REDIS_CLIENT: phpredis
  # REDIS_HOST: 127.0.0.1
  # REDIS_PASSWORD: null
  # REDIS_PORT: 6379

  # MAIL_MAILER: log
  # MAIL_SCHEME: null
  # MAIL_HOST: 127.0.0.1
  # MAIL_PORT: 2525
  # MAIL_USERNAME: null
  # MAIL_PASSWORD: null
  # MAIL_FROM_ADDRESS: "hello@example.com"
  # MAIL_FROM_NAME: "${APP_NAME}"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cnmu-config
