# apiVersion: v1
# stringData:
#   APP_KEY: something

#   DB_CONNECTION: mysql
#   DB_HOST: 127.0.0.1
#   DB_PORT: 3306
#   DB_DATABASE: idunno
#   DB_USERNAME: notroot,right?
#   DB_PASSWORD: ideallysecure

# kind: Secret
# metadata:
#   creationTimestamp: null
#   name: cnmu-secret
